box-background: 
  default: 'true'
  type: 'boolean'
  description: 'read true/false in scss'
title-string: 
  default: 'this is **bold** and this isn't''
  type: 'string'
  description: 'Use markdown in string'
